### ISSUE TITLE
 'PandaArm' object has no attribute '_tuck'

### ISSUE THREAD

**Issue by smihael** [justagist/panda_robot#1]
This package should be updated according to 
https://github.com/justagist/franka_ros_interface/commit/2451057250bb59b68d899db92a047c5722c4ad2b#diff-81b3b8a55d91d3417930f626a2cc595e

**Comment by justagist** [comment]
Where is the conflict in the name _tuck?

**Comment by justagist** [comment]
Thanks.  Fixed in #e473d21
