### ISSUE TITLE
AttributeError: 'PandaArm' object has no attribute 'set_EE_frame_to_link'

### ISSUE THREAD

**Issue by Sission** [justagist/panda_robot#10]
I am using 
Panda_robot v0.6.0; 
Panda_simulator melodic;
franka_ros_interface v0.6.0
libfranka 0.7.0
franka_ros 0.6.0

when I do 
>> python # start interactive python session; make sure the correct ros workspace is sourced.
>> import rospy
>> from panda_robot import PandaArm
>> rospy.init_node("panda_demo") # initialise ros node

>> r = PandaArm() # create PandaArm instance

It shows the error:
>>> r = PandaArm()
[INFO] [1618014242.316671, 112.310000]: Robot control running in Simulation Mode!
[INFO] [1618014242.464641, 112.417000]: Waiting for collision behaviour services...
[INFO] [1618014243.702680, 113.336000]: PandaArm: Collision Service Not found. It will not be possible to change collision behaviour of robot!
[INFO] [1618014243.740938, 113.366000]: FrankaControllerManagerInterface: cannot detect controller name under param /controllers_config/trajectory_controller
[INFO] [1618014243.756567, 113.376000]: FrankaControllerManagerInterface: cannot detect controller name under param /controllers_config/impedance_controller
[INFO] [1618014243.882530, 113.479000]: PandaArm: MoveGroup was not found! This is okay if moveit service is not required!
[INFO] [1618014243.985199, 113.552000]: GripperInterface: Waiting for gripper action servers... 
[INFO] [1618014243.998065, 113.557000]: GripperInterface: Gripper action servers found! 
Unknown tag "hardwareInterface" in /robot[@name='panda']/transmission[@name='panda_tran_1']/actuator[@name='panda_motor_1']
Unknown tag "hardwareInterface" in /robot[@name='panda']/transmission[@name='panda_tran_2']/actuator[@name='panda_motor_2']
Unknown tag "hardwareInterface" in /robot[@name='panda']/transmission[@name='panda_tran_3']/actuator[@name='panda_motor_3']
Unknown tag "hardwareInterface" in /robot[@name='panda']/transmission[@name='panda_tran_4']/actuator[@name='panda_motor_4']
Unknown tag "hardwareInterface" in /robot[@name='panda']/transmission[@name='panda_tran_5']/actuator[@name='panda_motor_5']
Unknown tag "hardwareInterface" in /robot[@name='panda']/transmission[@name='panda_tran_6']/actuator[@name='panda_motor_6']
Unknown tag "hardwareInterface" in /robot[@name='panda']/transmission[@name='panda_tran_7']/actuator[@name='panda_motor_7']
Unknown tag "hardwareInterface" in /robot[@name='panda']/transmission[@name='panda_leftfinger']/actuator[@name='panda_finger_joint1']
Unknown tag "hardwareInterface" in /robot[@name='panda']/transmission[@name='panda_rightfinger']/actuator[@name='panda_finger_joint2']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sission/proj_ws/src/panda_robot/src/panda_robot/panda_robot.py", line 107, in __init__
    self.set_EE_frame_to_link('panda_hand' if self.has_gripper else 'panda_link8')
AttributeError: 'PandaArm' object has no attribute 'set_EE_frame_to_link'

**Comment by Sission** [comment]
I believe it can be fixed by modifying line 107 to:
self.reset_EE_frame()

**Comment by justagist** [comment]
This issue should be fixed now hopefully with the latest changes in justagist/franka_ros_interface@4b074d74311ad2af240a521ccc3ccbbb5f59e350. Please pull the latest version of `franka_ros_interface` (branch `v0.6.0-dev`). Let me know if you face any further issues.

Also please note that updates and issues resolutions for v0.6.0 of `panda_robot` and `franka_ros_interface` will be slower and I may not be able to provide support immediately. Pull requests are most welcome!

**Comment by Sission** [comment]
Thanks for the update! I will try 0.7.1
