### ISSUE TITLE
HI I got a fatal error when catkin build

### ISSUE THREAD

**Issue by Sission** [justagist/panda_robot#4]
fatal error: franka_control/ErrorRecoveryAction.h: No such file or directory  #include <franka_control/ErrorRecoveryAction.h>           

Could you help me with this?

**Comment by justagist** [comment]
Please use the `v0.7.1` branch of the franka_ros_interface (`git checkout v0.7.1`) package in your workspace, and build again.

**Comment by Sission** [comment]
Thanks, that works for me.
However, it seems to have some texture issues when I run the demo python code:

[ERROR] [1606345135.771862743]: Error retrieving file [file:///opt/ros/melodic/share/franka_description/meshes/collision/link3.stl]: Couldn't open file /opt/ros/melodic/share/franka_description/meshes/collision/link3.stl

Also, I got a WARN 
[ WARN] [1606345157.126570625, 94.691000000]: Homing not implemented for simulator.
[ WARN] [1606345157.126619852, 94.691000000]: Your executeCallback did not set the goal to a terminal status.
This is a bug in your ActionServer implementation. Fix your code!
For now, the ActionServer will set this goal to aborted

**Comment by justagist** [comment]
The new version of franka_ros does not have the collision descriptions. 
You are using the old version of robot description package. Please update the `franka_panda_description` package by performing a git pull.

**Comment by Sission** [comment]
Thanks!

May I ask, the ee_pose() refers to which joint? the hand or the joint 7?
