### ISSUE TITLE
Quaternion Library

### ISSUE THREAD

**Issue by furkandurmus** [justagist/panda_robot#5]
Hello Saif

When I try to import panda_robot it throws me quaternion library error. Even I installed it via pip for python 2.7 it still raise the same error. I tried numpy-quaternion also, still getting the same error. Any suggestion would be highly appreciated.

Thanks

**Comment by justagist** [comment]
What is the error message? 
If you have installed numpy-quaternion, then you should be able to `import quaternion`.

**Comment by furkandurmus** [comment]
I figured out by installing manually from source code, thanks for your interest :)

Best.
